name: Bot3
on:
  push:
    branches: [stag]

env:
  TZ: America/Recife
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 525600

    steps:
      - name: Checkouts
        uses: actions/checkout@master
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Create swap (Avoid mk2fs issues)
        run: |
          sudo dd if=/dev/zero of=swap bs=4k count=1048576
          sudo mkswap swap
          sudo swapon swap

      - name: Setup git Environment
        run: |
          git config --global user.name "Daffety"
          git config --global user.email ${{ secrets.PVT_EM }}
          git config --global pull.rebase false
          git config --global credential.helper store
          echo "https://Daffety:${{ secrets.GH_TTH }}@github.com" > ~/.git-credentials

      - name: Setup Bobot Environment
        continue-on-error: true
        run: |
          mkdir configs && cd configs
          touch configs.prop
          touch allowed2port.json
          echo "bot-token=${{ secrets.GH }}" >> configs.prop
          echo "bot-username=veloshstagingbot" >> configs.prop
          echo "bot-master=1072790346" >> configs.prop
          echo "privateChat=-1001374650142" >> configs.prop
          echo "requestChat=-1001383418886" >> configs.prop
          echo "publicChannel=TrebleExperience" >> configs.prop
          echo "bot-sf-pass=${{ secrets.PASS_SF }}" >> sf-creds.prop
          echo "bot-sf-proj=trebleexperience" >> sf-creds.prop
          echo "bot-sf-user=velosh" >> sf-creds.prop
          echo "bot-announcement-id=-1001489409825" >> sf-creds.prop
          echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.prop
          echo "bot-send-announcement=true" >> sf-creds.prop
          echo '["918317361","1828939835","1263663104","739474399","932456186","576596376"]' >> allowed2port.json

      - name: Clone workflow
        continue-on-error: true
        run: |
          mkdir tmp && cd tmp
          git clone https://github.com/VeloshGSIs/Bot3-Workflow Bobot

      - name: Install tools/packages
        continue-on-error: true
        timeout-minutes: 5
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache expect aria2 unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev brotli liblz4-tool axel gawk aria2 detox cpio rename build-essential simg2img aria2 python3-pip tree

      - name: Setup Erfan GSIs Tool
        continue-on-error: true
        timeout-minutes: 2
        run: |
          git clone --recurse-submodules https://github.com/TrebleExperience/ErfanGSIs-TrebleExp-Old.git ErfanGSIs -b velan/stable
          pip3 install wheel setuptools
          pip3 install backports.lzma docopt zstandard bsdiff4 protobuf pycrypto
          sudo pip3 install --upgrade protobuf

      - name: Setup, Build & Run Java 16/Bot3 source
        continue-on-error: true
        timeout-minutes: 315
        run: |
          export ABC="$(pwd)"
          sudo mkdir -p /usr/java/oracle; cd /usr/java/oracle
          sudo wget 'https://github.com/VeloshGSIs/Bot3-Workflow/releases/download/J16/jdk-16.0.1_linux-x64_bin.tar.gz' -O linux.tar.gz >> /dev/null 2> /dev/null
          sudo tar -xzvf linux.tar.gz
          sudo update-alternatives --install "/usr/bin/java" "java" "/usr/java/oracle/jdk-16.0.1/bin/java" 1
          sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/oracle/jdk-16.0.1/bin/javac" 1
          export JAVA_HOME=/usr/java/oracle/jdk-16.0.1
          export PATH=$PATH:$JAVA_HOME/bin
          sudo dpkg --purge --force-depends ca-certificates-java
          sudo apt-get install ca-certificates-java -y
          cd ${ABC}
          git clone https://github.com/TrebleExperience/Bot3 Bot; cd Bot
          wget 'https://gist.githubusercontent.com/Velosh/95c9844c8a259fc99ec1f09c7c432781/raw/1f5ee87215c4b144bdc4674032e87d68df7fbd96/0001-Gradle-Patch-to-supports-lazy-method-for-Java-16-Vel.patch' -O 0001-Gradle-Patch-to-supports-lazy-method-for-Java-16-Vel.patch
          wget 'https://gist.githubusercontent.com/Velosh/6ad1a93fa8d3d78116b17fd34068da2b/raw/721b834ab23095dd2ee795bee2f2d888616378dd/0001-Bot-Use-.-as-default-prefix.patch' -O '0001-Bot-Use-.-as-default-prefix.patch'
          git am 0001-Gradle-Patch-to-supports-lazy-method-for-Java-16-Vel.patch
          rm -rf 0001-Gradle-Patch-to-supports-lazy-method-for-Java-16-Vel.patch
          ./gradlew shadowJar
          cd ../; mv Bot/build/libs/*.jar BoboBot.jar
          rm -rf Bot
          sudo /usr/java/oracle/jdk-16.0.1/bin/java -jar BoboBot.jar

      - name: Re-run Bot3 workflow
        continue-on-error: true
        timeout-minutes: 5
        run: |
          cd tmp/Bobot
          git commit --allow-empty -m "[LOOP] Re-run Bot3 workflow"
          git push -f
