name: Bot3
on:
  push:
    branches: [stag]

env:
  TZ: America/Recife
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 525600

    steps:
      - name: Checkouts
        uses: actions/checkout@master
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Create swap (Avoid mk2fs issues)
        run: |
          sudo dd if=/dev/zero of=swap bs=4k count=1048576
          sudo mkswap swap
          sudo swapon swap

      - name: Setup git Environment
        run: |
          git config --global user.name "Daffety"
          git config --global user.email ${{ secrets.PVT_EM }}
          git config --global pull.rebase false
          git config --global credential.helper store
          echo "https://Daffety:${{ secrets.GH_TTH }}@github.com" > ~/.git-credentials
          sudo echo "https://Daffety:${{ secrets.GH_TTH }}@github.com" > ~/.git-credentials

      - name: Clone workflow
        continue-on-error: true
        run: |
          mkdir tmp && cd tmp
          git clone https://github.com/VeloshGSIs/Bot3-Workflow Bobot

      - name: Install tools/packages
        continue-on-error: true
        timeout-minutes: 5
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache expect aria2 unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev brotli liblz4-tool axel gawk aria2 detox cpio rename build-essential simg2img aria2 python3-pip tree
          
      - name: Try to drop prebuilt all OpenJDKs
        run: |
          rm -rf /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
          sudo apt-get purge --purge openjdk* -y

      - name: Try to download GraalVM's JDK 16
        run: |
          cd /usr; sudo mkdir -p oracle/java/ && cd oracle/java/
          sudo wget 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java16-linux-amd64-21.2.0.tar.gz' -O graalvm-jdk16.tar.gz >> /dev/null 2>&1
          sudo tar -xzvf graalvm-jdk16.tar.gz >> /dev/null 2>&1 && sudo rm -f graalvm-jdk16.tar.gz
          export JAVA_HOME=/usr/oracle/java/graalvm-ce-java16-21.2.0
          export PATH=$PATH:$JAVA_HOME/bin
      
      - name: Set GraalVM (binaries) as default
        run: |
          sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/oracle/java/graalvm-ce-java16-21.2.0/bin/javac" 1
          sudo update-alternatives --install "/usr/bin/java" "java" "/usr/oracle/java/graalvm-ce-java16-21.2.0/bin/java" 1
          sudo update-alternatives --install "/usr/bin/gu" "gu" "/usr/oracle/java/graalvm-ce-java16-21.2.0/bin/gu" 1
      
      - name: Clone, Compile & Setup Bot続+t
        run: |
          git clone https://github.com/TrebleExperience/Bot3
          cd Bot3
          mkdir configs && cd configs
          touch configs.prop
          touch allowed2port.json
          echo "bot-token=${{ secrets.GH }}" >> configs.prop
          echo "bot-username=veloshstagingbot" >> configs.prop
          echo "bot-master=1072790346" >> configs.prop
          echo "privateChat=-1001374650142" >> configs.prop
          echo "requestChat=-1001383418886,-1001649321386" >> configs.prop
          echo "publicChannel=TrebleExperience" >> configs.prop
          echo "bot-sf-pass=${{ secrets.PASS_SF }}" >> sf-creds.prop
          echo "bot-sf-proj=trebleexperience" >> sf-creds.prop
          echo "bot-sf-user=velosh" >> sf-creds.prop
          echo "bot-announcement-id=-1001489409825" >> sf-creds.prop
          echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.prop
          echo "bot-send-announcement=true" >> sf-creds.prop
          echo '["918317361","1828939835","1263663104","739474399","932456186","576596376","2052221966"]' >> allowed2port.json
          
      - name: Install native-image & Rebuild Bot続+t prebuilt Jar as native code
        run: |
          sudo gu install native-image
          sudo update-alternatives --install "/usr/bin/native-image" "native-image" "/usr/oracle/java/graalvm-ce-java17-21.3.0/bin/native-image" 1
          cd Bot3/build/libs && native-image -jar *.jar

      - name: Setup our custom private ErfanGSIs
        continue-on-error: true
        timeout-minutes: 6
        run: |
          sudo apt install openjdk-8-jdk -y >> /dev/null 2>&1
          cd Bot3/build/libs
          git clone --recurse-submodules https://github.com/TrebleExperience/EXP-TrebleExp.git ErfanGSIs -b velan/stable
          pip3 install wheel setuptools
          pip3 install backports.lzma docopt zstandard bsdiff4 protobuf pycrypto
          sudo pip3 install --upgrade protobuf
          cd ErfanGSIs/tools/ROM_resigner && git reset --hard HEAD~2

      - name: Run the Bot続+t
        continue-on-error: true
        timeout-minutes: 315
        run: cd Bot3/build/libs && sudo ./BoboBot-1.7.0-all

      - name: Re-run Bot3 workflow
        continue-on-error: true
        timeout-minutes: 5
        run: |
          cd tmp/Bobot
          git commit --allow-empty -m "[LOOP] Re-run Bot続+t workflow"
          git push -f
